// Generated by CoffeeScript 1.10.0
window.count = 1;

$().ready(function() {
  return setInterval(function() {
    window.count++;
    if (window.count > 20) {
      window.count = 1;
    }
    return window.history.replaceState('', '', '/' + Array(window.count + 1).join('ε=') + '┏(ﾟロﾟ;)┛');
  }, 50);
});
